services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JDBC_DATABASE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=false # Corrected port
      JDBC_DATABASE_USERNAME: root
      JDBC_DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    depends_on:
      db:
        condition: service_healthy

    networks:
      - springboot-mysql-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 10
      interval: 3s
      timeout: 30s
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - springboot-mysql-network
volumes:
  db_data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network
    driver: bridge